print("Patricia MOnick Longcayana")
print("PAye mogpog marinduque")
print("November 20 2001")
print("college of engineering information technology and industrial technology")
print("bachelor of science in information technology")
print("BSIT2D")
print("swimming")
print("eating")
print("listening to music")
print("Playing online games")
print('playing basketball')